name: quiz_flutter
description: quiz app with flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  built_value: ^8.1.0
  built_collection: ^5.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  built_value_generator: ^8.1.0

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/flower_ruppy.jpeg

  fonts:
    - family: OpenSans
      fonts:
         - asset: assets/fonts/OpenSans-Regular.ttf
         - asset: assets/fonts/OpenSans-Bold.ttf
           weight: 700
    - family: Quicksand
      fonts:
         - asset: assets/fonts/Quicksand-Regular.ttf
         - asset: assets/fonts/Quicksand-Bold.ttf
           weight: 700
